Repository prgrms-web-devcourse/Team-Saiko-BidMarket-FE, pull requests merged in 2022-08, with the labels that each got.

#12 [BM-137] 검색 결과 페이지 레이아웃 구현
  components/Products/BidFilterCheckBox.tsx
  components/Products/FilterButton.tsx
  components/Products/index.tsx
  components/common/SEO/index.tsx
  pages/products/index.tsx
Labels: 리뷰 요청, 프론트

#14 [BM-146] 회원 정보 입찰한 상품 페이지 레이아웃 구현
  components/User/NoBidProducts.tsx
  components/User/index.tsx
  pages/user/[userId]/products/bid/index.tsx
Labels: 리뷰 요청, 프론트

#15 [BM-147] 회원 정보 찜한 상품 페이지 레이아웃 구현
  components/User/NoLikeProducts.tsx
  components/User/index.tsx
  pages/user/[userId]/products/like/index.tsx
Labels: 리뷰 요청, 프론트

#18 [BM-140] 1차 API 모듈화 진행
  .gitignore
  apis/api/product/index.ts
  apis/index.ts
  apis/utils/instance.ts
  apis/utils/interceptors.ts
  apis/utils/storage.ts
  package-lock.json
  package.json
Labels: 리뷰 요청, 프론트

#16 [BM-148] 회원 정보 판매한 상품 페이지 (타인 계정) 레이아웃 구현
  components/User/NoSellProductsOtherUsers.tsx
  components/User/index.tsx
  pages/user/[userId]/products/sell/index.tsx
  public/svg/noneProductOther.svg
Labels: 리뷰 요청, 프론트

#19 [BM-144] 유저 정보 페이지 레이아웃 구현
  components/User/ProductMenuItem.tsx
  components/User/ProductMenuList.tsx
  components/User/UserProfileEditButton.tsx
  components/User/UserProfileInformation.tsx
  components/User/index.tsx
  pages/user/[userId]/index.tsx
  public/svg/bidProductMenuIcon.svg
  public/svg/likeProductMenuIcon.svg
  public/svg/sellProductMenuIcon.svg
Labels: 리뷰 요청, 프론트

#21 [BM-150] 2차 API 모듈화 진행(스토리지와 토큰여부 확인)
  apis/api/product/index.ts
  apis/utils/authInstance.ts
  apis/utils/baseInstance.ts
  apis/utils/instance.ts
  apis/utils/interceptors.ts
Labels: 리뷰 요청, 프론트

#22 [BM-175] 이미지 파일 S3로 업로드
  components/ProfileEdit/.ProfileImageUpload.tsx.swp
  components/ProfileEdit/EditForm.tsx
  components/ProfileEdit/ProfileImageUpload.tsx
  package-lock.json
  package.json
  pages/api/s3/image/index.ts
Labels: 리뷰 요청, 프론트

#26 [BM-200] 메인 테마 밝은 회색 테마 추가
  components/User/NoBidProducts.tsx
  components/User/NoLikeProducts.tsx
  components/User/NoSellProducts.tsx
  pages/404/index.tsx
  pages/500/index.tsx
  pages/_app.tsx
Labels: 리뷰 요청, 프론트

#23 [BM-54] 로그인 URL 변경 및 토큰 저장 구현
  apis/utils/storage.ts
  components/Login/GoogleLoginButton.tsx
  pages/auth/index.tsx
Labels: 리뷰 요청, 프론트

#28 [BM-123] 상품 상세페이지 상품 조회 기능 구현과 API 연동
  apis/api/product/index.ts
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductImage.tsx
  components/ProductDetail/ProductInfo.tsx
  components/ProductDetail/ProductSeller.tsx
  components/common/Card/index.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/products/[productId].tsx
  pages/products/index.tsx
  types/product/index.ts
  types/user/index.ts
  utils/index.ts
  utils/priceFormat.ts
  utils/remainedTimeFormat.ts
Labels: 리뷰 요청, 프론트

#27 [BM-118] 상세 등록 페이지 기능 구현 (임시)
  components/CreateProduct/AddProductDescription.tsx
  components/CreateProduct/AddProductImage.tsx
  components/CreateProduct/AddProductImageUpload.tsx
  components/CreateProduct/AddProductLocation.tsx
  components/CreateProduct/AddProductMinimumPrice.tsx
  components/CreateProduct/AddProductTitle.tsx
  components/CreateProduct/ProductLabel.tsx
  components/CreateProduct/SubmitButton.tsx
  components/CreateProduct/index.tsx
  components/common/Category/index.tsx
  pages/product/index.tsx
Labels: 리뷰 요청, 프론트

#29 [BM-209] 메인페이지 로그인 토큰 유무에 따른 레이아웃 구현
  components/Main/LoginButton.tsx
  components/Main/MainHeader.tsx
Labels: 리뷰 요청, 프론트

#30 [BM-210] 경매가 종료된 상품에 대한 예외 버그 픽스
  utils/remainedTimeFormat.ts
Labels: 리뷰 요청, 프론트

#31 [BM-120] 메인 페이지 API 연동 1차
  apis/api/product/index.ts
  apis/utils/authInstance.ts
  apis/utils/baseInstance.ts
  components/common/Card/index.tsx
  pages/index.tsx
  pages/products/index.tsx
  types/product/index.ts
Labels: 리뷰 요청, 프론트

#32 [BM-171] 회원 정보페이지 API 연동 및 분기처리
  apis/api/user/index.ts
  pages/user/[userId]/index.tsx
Labels: 리뷰 요청, 코칭 요청, 프론트

#33 [BM-239] 상품없는 페이지 중복 코드 제거
  components/User/NoBidProducts.tsx
  components/User/NoLikeProducts.tsx
  components/User/NoProducts.tsx
  components/User/NoSellProducts.tsx
  components/User/NoSellProductsOtherUsers.tsx
  components/User/index.tsx
  pages/user/[userId]/products/bid/index.tsx
  pages/user/[userId]/products/like/index.tsx
  pages/user/[userId]/products/sell/index.tsx
Labels: 리뷰 요청, 프론트

#35 [BM-63] API를 통해 유저 정보를 변경
  apis/api/user/index.ts
  components/ProfileEdit/EditForm.tsx
  hooks/useLoginUser.ts
  pages/user/[userId]/edit/index.tsx
Labels: 리뷰 요청, 프론트

#34 [BM-234] 로그아웃 버튼 및 기능 구현
  components/common/Header/LogoutButton.tsx
  components/common/Header/SideBar.tsx
Labels: 리뷰 요청, 프론트

#37 [BM-235] 상품 상세 페이지 작은 이슈들 처리와 유저 검증 API 연결
  apis/index.ts
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductSeller.tsx
  components/ProfileEdit/EditForm.tsx
  pages/products/[productId].tsx
Labels: 리뷰 요청, 프론트

#36 [BM-184] 메인페이지 header 사용자 프로필이미지로 변경
  components/Main/MainHeader.tsx
Labels: 리뷰 요청, 프론트

#40 [BM-261] 수정된 유저 api 반영
  apis/api/user/index.ts
  hooks/useLoginUser.ts
  pages/user/[userId]/edit/index.tsx
  pages/user/[userId]/index.tsx
  types/user/index.ts
Labels: 프론트

#41 [BM-256] useLoginUser 훅 개선과 바뀐 API 명세 반영
  components/Main/MainHeader.tsx
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductSeller.tsx
  hooks/useLoginUser.ts
  pages/products/[productId].tsx
  pages/user/[userId]/edit/index.tsx
  pages/user/[userId]/index.tsx
Labels: 리뷰 요청

#39 [BM-158] 입찰 기능 API 구현
  apis/api/bid/index.ts
  apis/index.ts
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductBidDrawer.tsx
  utils/format/priceFormat.ts
  utils/format/remainedTimeFormat.ts
  utils/index.ts
  utils/validation/biddingPriceValidation.ts
Labels: 리뷰 요청

#43 [BM-236] 알림 페이지 레이아웃 구현
  apis/api/product/index.ts
  components/Main/MainHeader.tsx
  components/User/NoNotifications.tsx
  components/User/NotificationCard.tsx
  components/User/index.tsx
  components/common/Header/GoBackIcon.tsx
  components/common/ProductCard/ProductCardImage.tsx
  components/common/ProductCard/index.tsx
  components/common/index.tsx
  hooks/useForm.ts
  pages/index.tsx
  pages/products/index.tsx
  pages/user/[userId]/notifications/index.tsx
  public/svg/noneNotification.svg
  utils/format/distanceTimeFormat.ts
Labels: 리뷰 요청

#42 [BM-230] 변경된 회원 정보 페이지 레이아웃 반영
  components/User/ProductMenuItem.tsx
  components/User/ProductMenuList.tsx
  components/User/UserSetting.tsx
  components/User/index.tsx
  pages/user/[userId]/index.tsx
  public/svg/logout.svg
Labels: 리뷰 요청

#44 [BM-232] 입찰한 상품 목록 API 연동
  apis/api/user/index.ts
  pages/user/[userId]/products/bid/index.tsx
Labels: 리뷰 요청

#45 [BM-274] 채팅 목록 페이지 레이아웃
  components/Main/MainHeader.tsx
  components/User/ChattingCard.tsx
  components/User/NoChatting.tsx
  components/User/index.tsx
  pages/user/[userId]/chattings/index.tsx
  public/svg/noneChatting.svg
Labels: 리뷰 요청

#38 [BM-139] 검색 결과 페이지 API 연동
  components/Main/MainHeader.tsx
  components/Products/BidFilterCheckBox.tsx
  components/Products/FilterButton.tsx
  components/common/SearchInput/index.tsx
  pages/index.tsx
  pages/products/index.tsx
  types/categoryOption/index.ts
  types/sortOption/index.ts
  utils/index.ts
  utils/transformCategoryOptions.ts
  utils/transformSortOptions.ts
Labels: 리뷰 요청

#46 [BM-286] react-query useInfiniteQuery 적용
  apis/api/product/index.ts
  components/common/ProductCardContainer/index.tsx
  components/common/index.tsx
  hooks/queries/index.ts
  hooks/queries/product/useGetProducts.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/products/index.tsx
Labels: 리뷰 요청

#47 [BM-296] 상세페이지 남은시간 실시간 반영
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductBidDrawer.tsx
  components/ProductDetail/ProductBidRemainedTime.tsx
  components/ProductDetail/ProductInfo.tsx
  components/ProductDetail/index.tsx
  components/User/NotificationCard.tsx
  components/common/ProductCard/index.tsx
  hooks/useInterval.ts
  hooks/useIntervalComparedValue.ts
  utils/format/remainedTimeFormat.ts
Labels: 리뷰 요청

#48 [BM-275] 채팅방 목록 페이지 API 연동
  apis/api/user/index.ts
  pages/user/[userId]/chat/index.tsx
  pages/user/[userId]/chattings/index.tsx
  types/chatRooms/index.ts
Labels: 리뷰 요청

#49 [BM-244] 상품 등록 페이지 이미지 등록 및 세부 기능 구현
  apis/api/product/index.ts
  components/CreateProduct/AddProductCategory.tsx
  components/CreateProduct/AddProductDescription.tsx
  components/CreateProduct/AddProductImage.tsx
  components/CreateProduct/AddProductImageUpload.tsx
  components/CreateProduct/AddProductMinimumPrice.tsx
  components/CreateProduct/AddProductTitle.tsx
  components/CreateProduct/index.tsx
  components/Products/FilterButton.tsx
  components/common/Category/index.tsx
  pages/product/index.tsx
  tsconfig.json
Labels: 리뷰 요청

#50 [BM-297] 메인, 검색 페이지 무한스크롤 적용 + 메인페이지 로고 적용
  apis/api/product/index.ts
  components/Main/Banner.tsx
  components/Main/MainHeader.tsx
  components/common/ProductCard/index.tsx
  hooks/queries/index.ts
  hooks/queries/product/useGetProductsByKeyword.ts
  package-lock.json
  package.json
  pages/index.tsx
  pages/login/index.tsx
  pages/products/index.tsx
  public/svg/bidmarket-bibi.svg
  public/svg/bidmarket-login.svg
  public/svg/bidmarket-logo.svg
Labels: 리뷰 요청

#52 [BM-305] 알림페이지 API 연동 + 무한 쿼리
  apis/api/notification/index.tsx
  apis/index.ts
  components/User/NoNotifications.tsx
  components/User/NotificationCard.tsx
  hooks/queries/index.ts
  hooks/queries/notification/useGetNotifications.tsx
  pages/user/[userId]/notifications/index.tsx
  types/notification/index.ts
Labels: 리뷰 요청

#51 [BM-270] 입찰, 낙찰 UI 및 기능 분기처리
  apis/api/bid/index.ts
  components/ProductDetail/ProductBid.tsx
  components/ProductDetail/ProductBidDrawer.tsx
  components/ProductDetail/ProductBidEndTextByStatus.tsx
  utils/index.ts
  utils/toast/index.ts
  utils/validation/biddingPriceValidation.ts
Labels: 리뷰 요청

#53 [BM-318] 알림 페이지 무한 스크롤 적용, 검색페이지에서 무조건 홈으로 가도록 분기처리
  components/common/Header/GoBackIcon.tsx
  pages/user/[userId]/notifications/index.tsx
Labels: 리뷰 요청

#54 [BM-328] 헤더 타이틀 공통 컴포넌트로 분리
  components/Main/MainHeader.tsx
  components/ProfileEdit/ProfileEditHeader.tsx
  components/common/Header/HeaderTitle.tsx
  components/common/index.tsx
  pages/login/index.tsx
  pages/product/index.tsx
  pages/products/index.tsx
  pages/user/[userId]/chat/index.tsx
  pages/user/[userId]/index.tsx
  pages/user/[userId]/notifications/index.tsx
  pages/user/[userId]/products/bid/index.tsx
  pages/user/[userId]/products/like/index.tsx
  pages/user/[userId]/products/sell/index.tsx
Labels: 리뷰 요청

#55 [BM-326] 경매 종료 후 1분 대기 로직 구현
  components/ProductDetail/ProductBid.tsx
Labels: 리뷰 요청

#56 [BM-325] 낙찰 했을 경우 채팅 버튼 연결과 UI 적용
  components/ProductDetail/ProductBid.tsx
  components/common/ProductCard/index.tsx
Labels: 리뷰 요청

#57 [BM-333] 상품 상세 페이지 페이지 넘기는 기능 구현
  components/ProductDetail/ProductImage.tsx
  pages/products/[productId].tsx
Labels: 리뷰 요청

#58 [BM-334] 알림 확인(읽음) API 연동
  apis/api/notification/index.tsx
  components/User/NotificationCard.tsx
  pages/user/[userId]/notifications/index.tsx
  types/notification/index.ts
Labels: 리뷰 요청

#59 [BM-341] 회원 정보 페이지 3차 UI 반영 및 로그아웃, 회원탈퇴 페이지 구현
  components/User/ProductMenuItem.tsx
  components/User/ProductMenuList.tsx
  components/User/UserProfileEditButton.tsx
  components/User/UserProfileEditOrReportButton.tsx
  components/User/UserSetting.tsx
  components/User/index.tsx
  pages/user/[userId]/index.tsx
  pages/user/[userId]/setting/index.tsx
Labels: 리뷰 요청

#61 [BM-343] 검색 페이지 Drawer 선택된 옵션 체크 및 상품 상세 페이지 상품 사진 갯수에 따라 분기처리
  components/ProductDetail/ProductImage.tsx
  components/Products/FilterButton.tsx
  pages/products/[productId].tsx
Labels: 리뷰 요청

#62 [BM-342] 회원탈퇴 API 연동
  apis/api/user/index.ts
  pages/user/[userId]/setting/index.tsx
Labels: 리뷰 요청

#60 [BM-339] 상품 신고하기 레이아웃(유저와 상품 구분)
  components/Report/ProductInfo.tsx
  components/Report/ReportForm.tsx
  components/Report/UserInfo.tsx
  components/Report/index.tsx
  pages/products/[productId].tsx
  pages/reports/index.tsx
  pages/user/[userId]/index.tsx
  public/svg/siren.svg
Labels: 리뷰 요청

#63 [BM-346] 신고하기(상품, 유저) API 연동
  apis/api/report/index.tsx
  apis/index.ts
  components/Report/ReportCondition.tsx
  components/Report/ReportForm.tsx
  components/Report/ReportTitle.tsx
  components/Report/index.tsx
  hooks/useForm.ts
  pages/products/[productId].tsx
  pages/reports/index.tsx
  pages/user/[userId]/index.tsx
  utils/validation/reportsValidation.ts
Labels: 리뷰 요청

#65 [BM-302] STOMP 프로토콜로 채팅 기능 구현
  apis/api/user/index.ts
  components/User/ChattingCard.tsx
  hooks/useStomp.ts
  next.config.js
  package-lock.json
  package.json
  pages/user/[userId]/chat/[chatRoomId]/index.tsx
  pages/user/[userId]/chat/index.tsx
  types/chatMessages/index.ts
Labels: 리뷰 요청

#64 [BM-276] 회원 정보 (판매한 상품, 입찰한 상품) 목록 조회 무한 스크롤 적용
  apis/api/user/index.ts
  components/User/ProductMenuItem.tsx
  components/User/ProductMenuList.tsx
  hooks/queries/index.ts
  hooks/queries/user/useGetUserBidProducts.ts
  hooks/queries/user/useGetUserSellProducts.ts
  pages/index.tsx
  pages/products/index.tsx
  pages/user/[userId]/index.tsx
  pages/user/[userId]/notifications/index.tsx
  pages/user/[userId]/products/bid/index.tsx
  pages/user/[userId]/products/sell/index.tsx
Labels: 리뷰 요청

#66 [BM-271] 찜하기, 찜취소하기 API 연동과 메인 페이지 찜 개수 연결
  apis/api/heart/index.tsx
  apis/index.ts
  components/ProductDetail/ProductHeart.tsx
  components/ProductDetail/index.tsx
  components/common/ProductCard/index.tsx
  pages/products/[productId].tsx
  types/product/index.ts
Labels: 리뷰 요청

#68 [BM-350] 유저 찜 여부에 따른 API 분기처리와 ProductCard 컴포넌트 스타일 수정
  apis/api/heart/index.tsx
  components/ProductDetail/ProductHeart.tsx
  components/common/ProductCard/index.tsx
Labels: 리뷰 요청

#69 [BM-351] 만료 후 1분 배치 시간 동안 사용자 메시지 출력 버그 픽스
  components/ProductDetail/ProductBid.tsx
Labels: 리뷰 요청

#70 [BM-317] 상품 등록 시 이미지 스크롤, 폼 입력에 대한 검증
  apis/api/product/index.ts
  components/CreateProduct/AddProductCategory.tsx
  components/CreateProduct/AddProductDescription.tsx
  components/CreateProduct/AddProductImage.tsx
  components/CreateProduct/AddProductImageUpload.tsx
  components/CreateProduct/AddProductMinimumPrice.tsx
  components/CreateProduct/AddProductTitle.tsx
  components/Products/FilterButton.tsx
  pages/product/index.tsx
  public/CreateProduct/cp1.png
  public/CreateProduct/cp2.png
  public/CreateProduct/cp3.png
  public/CreateProduct/cp4.png
  public/CreateProduct/cp5.png
  utils/validation/productFormValidation.ts
Labels: 리뷰 요청

#71 [BM-332] 회원 정보 찜한 상품 페이지 API 연동 및 무한 스크롤 적용
  apis/api/user/index.ts
  hooks/queries/index.ts
  hooks/queries/user/useGetUserLikeProducts.ts
  pages/user/[userId]/products/like/index.tsx
Labels: 리뷰 요청

#73 [BM-360] 비딩 금액 조회 변경된 API 반영과 상세페이지 이미지, 아이콘 색 변경
  components/ProductDetail/ProductBidDrawer.tsx
  components/ProductDetail/ProductImage.tsx
  components/common/Header/GoBackIcon.tsx
  pages/products/[productId].tsx
  public/svg/siren-light.svg
Labels: 리뷰 요청

#72 [BM-362] 상품 등록 시 생성 및 상세페이지로 이동, 이미지에 대한 버그 수정, 폼 검증 버그 수정
  components/CreateProduct/AddProductImageUpload.tsx
  pages/product/index.tsx
  utils/validation/productFormValidation.ts
Labels: 리뷰 요청

#75 [BM-361] SEO에 새로 바뀐 슬로건 적용
  README.md
  components/Login/Phrases.tsx
  components/Main/Banner.tsx
  components/common/SEO/index.tsx
Labels: 리뷰 요청

#78 [BM-353] bucket url 환경변수로 설정과 채팅방 메시지 변경, 상품 등록 이미지 버그 픽스
  components/ChatRoom/ChatInput.tsx
  components/CreateProduct/AddProductDescription.tsx
  components/CreateProduct/AddProductImageUpload.tsx
  components/CreateProduct/AddProductLocation.tsx
  components/CreateProduct/AddProductMinimumPrice.tsx
  components/CreateProduct/AddProductTitle.tsx
  components/ProfileEdit/ProfileImageUpload.tsx
  components/User/ChattingCard.tsx
  next.config.js
  pages/product/index.tsx
  pages/user/[userId]/chat/[chatRoomId]/index.tsx
  pages/user/[userId]/setting/index.tsx
  utils/validation/productFormValidation.ts
Labels: 리뷰 요청
